version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - 03 - Maintenance
  ignore:
  - dependency-name: hypothesis
    versions:
    - 6.0.3
    - 6.1.1
    - 6.2.0
    - 6.3.0
    - 6.3.4
    - 6.6.0
    - 6.8.1
    - 6.8.3
    - 6.8.4
    - 6.9.1
  - dependency-name: pydata-sphinx-theme
    versions:
    - 0.4.2
    - 0.4.3
    - 0.5.0
    - 0.5.2
    - 0.6.0
  - dependency-name: setuptools
    versions:
    - 52.0.0
    - 53.0.0
    - 54.0.0
    - 54.1.1
    - 54.2.0
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: cython
    versions:
    - 0.29.22
  - dependency-name: pytz
    versions:
    - "2021.1"
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-cov
    versions:
    - 2.11.1
  - dependency-name: mypy
    versions:
    - "0.800"
  commit-message:
    prefix: MAINT
